# Site settings
title: Caroline Weis
description: 'Welcome to my personal website. I am a senior machine learning engineer and team lead at gsk.ai. In 2021, I completed my PhD in Machine Learning for Computational Biology and Healthcare at ETH Zurich. This website is still under construction, but you will find some more information about my work in the blog section.'
url: 'https://cvweis.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Caroline Weis'
  email: carolinevweis@gmail.com
  cv_path: assets/CV_230629.pdf
  github_username:  cvweis
  linkedin_username:  caroline-weis-2b085995

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
