# Site settings
title: Caroline Weis
description: 'Welcome to the personal website of Caroline Weis. I am currently working as a machine learning engineer at gsk.ai. This website is still under construction, so bare with me until everything is set up.'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/jekyll-uno'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Caroline Weis'
  email: carolinevweis@gmail.com
  github_username:  cvweis
  linkedin_username:  caroline-weis-2b085995

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
